### ISSUE TITLE
Flow V2 

### ISSUE THREAD

**Issue by 2075** [gamedaoco/gamedao-protocol#61]
## Context

Flow pallet needs further development to be fully functional and configurable.

- [x] campaign settlement
- [ ] campaign creator deposit in governance currency
- [ ] campaign completion and emptied treasury resulting in return of the deposit
- [ ] campaign treasury accepting a configured payment currency for contributions
- [ ] campaign creation only when requirements are met [ verified, min rep, min trust ]
- [ ] unlock treasury based on vesting schedule
- [ ] unlock treasury based on accepted milestone through an acceptance vote
- [ ] unlock treasury based on accepted milestone through conviction vote
- [ ] drop campaign specific item on campaign settlement to contributor
- [ ] drop campaign specific item on project/milestone completion to contributor

Please add based on discovery of planned / required features.
